### ISSUE TITLE
Please share share the code 

### ISSUE THREAD

**Issue by Kazimbalti** [DanielrdMorais/SelfDrivingMPC#1]
Hello sir
Please, if possible, share the code of this simulation.
I would be much grateful to you.
My email:
kazimciit@gmail.com

Regards
kazim

**Comment by gustavomoers** [comment]
Hello,

if possible I would like to see the code as well.
email: gustavomoers@outlook.com

Thank you in advance,
Regards,
Gustavo

**Comment by sua7777** [comment]
Hi Sir,

Please share the code for MPC in CARLA if possible.

suamng.de@gmail.com

Best regards,
Sumit

**Comment by DanielrdMorais** [comment]
I invite you to review my [paper](https://ieeexplore.ieee.org/document/9784788) which comprehensively presents the outcomes and insights derived from my work.
